trigger:
  branches:
    include:
      - feature/gunjan

variables:
  - group: My-Variable


stages:
- stage: PreCommit
  jobs:
  - job: PreCommit
    pool:
      name: My-Self-Agent
    steps:
      - task: TerraformInstaller@1
        displayName: TF-Install
        inputs:
          terraformVersion: 'latest'
 
      - task: TerraformTask@5
        displayName: TF-Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work-Direct)
          backendServiceArm: $(ARM-service_connection)
          backendAzureRmResourceGroupName: $(BackendRG)
          backendAzureRmStorageAccountName: '$(BackendSTG)'
          backendAzureRmContainerName: '$(BackendCONT)'
          backendAzureRmKey: '$(BackendKEY)'

      - task: TerraformTask@5
        displayName: TF-Validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(Work-Direct)'
          environmentServiceNameAzureRM: $(ARM-service_connection)
           
      - task: TerraformTask@5
        displayName: TF-Format
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: '$(Work-Direct)'
          outputTo: 'console'
          customCommand: 'fmt'
          environmentServiceNameAzureRM: $(ARM-service_connection)

# scan job
  - job: ScanJob
    displayName: scanning..
    dependsOn: PreCommit
    condition: succeeded()
    pool:
      name: My-Self-Agent

    steps:
      - checkout: self
      - script: |
          tflint --init
          tflint
        displayName: "Run TFLint"
        workingDirectory: $(Work-Direct)
        continueOnError: true
  
      - task: tfsec@1
        displayName: "run tfsec"
        inputs:
          version: 'v1.26.0'
          dir: '$(Work-Direct)'
          

      - script: |
          checkov -d .
        displayName: "Run Checkov"
        workingDirectory: $(Work-Direct)
        continueOnError: true 

      - script: |
          trufflehog filesystem .
          displayName: "Run TruffleHog"
        workingDirectory: '$(Work-Direct)'
        continueOnError: true

  - job: costing
    displayName: infra_costing
    dependsOn: ScanJob 
    condition: succeeded()
    pool:
      name: My-Self-Agent

    steps:
      - checkout: self    
      - task: PowerShell@2
        displayName: Infracost analysis
        continueOnError: true
        inputs:
         targetType: 'inline'
         script: |
           Write-Host "API Key = $Env:api_key"
           infracost breakdown --path=$(Work-Direct
         workingDirectory: '$(Work-Direct)'
        
- stage: BuildPlan
  displayName: build_plan_stage
  dependsOn: PreCommitStage
  condition: succeeded() 
  pool:
    name: My-Self-Agent
  jobs:
    - job: BuildPlanJob
      displayName: Build_plan_job

      steps:
      - task: TerraformInstaller@1
        displayName: TF-Install
        inputs:
          terraformVersion: 'latest'
 
      - task: TerraformTask@5
        displayName: TF-Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work-Direct)
          backendServiceArm: $(ARM-service_connection)
          backendAzureRmResourceGroupName: $(BackendRG)
          backendAzureRmStorageAccountName: '$(BackendSTG)'
          backendAzureRmContainerName: '$(BackendCONT)'
          backendAzureRmKey: '$(BackendKEY)'

      - task: TerraformTask@5
        displayName: terraform_plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(Work-Direct)'
          environmentServiceNameAzureRM: $(ARM-service_connection)
          commandOptions: -out=tfplan
      - task: PublishPipelineArtifact@1
        inputs:
          # targetPath: '$(Pipeline.Workspace)'
          targetPath: '$(Work-Direct)/tfplan'
          artifact: 'build_tf_plan'
          publishLocation: 'pipeline'
     
          
# Manual validation
- stage: ManualValidation
  displayName: Manual_validation
  pool: server
  dependsOn: BuildPlan
  condition: succeeded()
  jobs:
    - job: approval
      displayName: validation required
      steps:
        - task: ManualValidation@1
          displayName: approval
          inputs:
            notifyUsers: gunjan.r.singh@outlook.com
            approvers: gunjan.r.singh@outlook.com



- stage: ApplyStage
  dependsOn: ManualValidation
  condition: succeeded()
  pool:
     name: My-Self-Agent 
  jobs:
    - job: ApplyJob
      displayName: apply_job
      steps:
      - task: TerraformInstaller@1
        displayName: TF-Install
        inputs:
          terraformVersion: 'latest'
 
      - task: TerraformTask@5
        displayName: TF-Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work-Direct)
          backendServiceArm: $(ARM-service_connection)
          backendAzureRmResourceGroupName: $(BackendRG)
          backendAzureRmStorageAccountName: '$(BackendSTG)'
          backendAzureRmContainerName: '$(BackendCONT)'
          backendAzureRmKey: '$(BackendKEY)'

      - task: DownloadPipelineArtifact@2
        displayName: download_artifacts
        inputs:
          buildType: 'current'
          artifactName: 'build_tf_plan'
          targetPath: '$(Work-Direct)/tf_plan'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(Work-Direct)'
          environmentServiceNameAzureRM: 'service_connection_ado'
          commandOptions: '$(Work-Direct)/tfplan -auto-approve'